/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminAuthRouteImport } from './routes/admin-auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as AuthenticatedCoordinatorRouteImport } from './routes/_authenticated/coordinator'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCoordinatorIndexRouteImport } from './routes/_authenticated/coordinator.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as MDriverTokenRouteImport } from './routes/m.driver.$token'
import { Route as MClientTokenRouteImport } from './routes/m/client/$token'
import { Route as AuthenticatedCoordinatorStatementsRouteImport } from './routes/_authenticated/coordinator.statements'
import { Route as AuthenticatedCoordinatorPortalLinksRouteImport } from './routes/_authenticated/coordinator.portal-links'
import { Route as AuthenticatedCoordinatorPendingRouteImport } from './routes/_authenticated/coordinator.pending'
import { Route as AuthenticatedCoordinatorMyDrivingRouteImport } from './routes/_authenticated/coordinator.my-driving'
import { Route as AuthenticatedCoordinatorLabelsRouteImport } from './routes/_authenticated/coordinator.labels'
import { Route as AuthenticatedCoordinatorIncomingRouteImport } from './routes/_authenticated/coordinator.incoming'
import { Route as AuthenticatedCoordinatorDriversRouteImport } from './routes/_authenticated/coordinator.drivers'
import { Route as AuthenticatedCoordinatorCollaborateRouteImport } from './routes/_authenticated/coordinator.collaborate'
import { Route as AuthenticatedCoordinatorCalendarRouteImport } from './routes/_authenticated/coordinator.calendar'
import { Route as AuthenticatedAdminLedgerRouteImport } from './routes/_authenticated/admin.ledger'
import { Route as AuthenticatedAdminFeatureCostsRouteImport } from './routes/_authenticated/admin.feature-costs'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin-auth',
  path: '/admin-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoordinatorRoute =
  AuthenticatedCoordinatorRouteImport.update({
    id: '/coordinator',
    path: '/coordinator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoordinatorIndexRoute =
  AuthenticatedCoordinatorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCoordinatorRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const MDriverTokenRoute = MDriverTokenRouteImport.update({
  id: '/m/driver/$token',
  path: '/m/driver/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MClientTokenRoute = MClientTokenRouteImport.update({
  id: '/m/client/$token',
  path: '/m/client/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoordinatorStatementsRoute =
  AuthenticatedCoordinatorStatementsRouteImport.update({
    id: '/statements',
    path: '/statements',
    getParentRoute: () => AuthenticatedCoordinatorRoute,
  } as any)
const AuthenticatedCoordinatorPortalLinksRoute =
  AuthenticatedCoordinatorPortalLinksRouteImport.update({
    id: '/portal-links',
    path: '/portal-links',
    getParentRoute: () => AuthenticatedCoordinatorRoute,
  } as any)
const AuthenticatedCoordinatorPendingRoute =
  AuthenticatedCoordinatorPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthenticatedCoordinatorRoute,
  } as any)
const AuthenticatedCoordinatorMyDrivingRoute =
  AuthenticatedCoordinatorMyDrivingRouteImport.update({
    id: '/my-driving',
    path: '/my-driving',
    getParentRoute: () => AuthenticatedCoordinatorRoute,
  } as any)
const AuthenticatedCoordinatorLabelsRoute =
  AuthenticatedCoordinatorLabelsRouteImport.update({
    id: '/labels',
    path: '/labels',
    getParentRoute: () => AuthenticatedCoordinatorRoute,
  } as any)
const AuthenticatedCoordinatorIncomingRoute =
  AuthenticatedCoordinatorIncomingRouteImport.update({
    id: '/incoming',
    path: '/incoming',
    getParentRoute: () => AuthenticatedCoordinatorRoute,
  } as any)
const AuthenticatedCoordinatorDriversRoute =
  AuthenticatedCoordinatorDriversRouteImport.update({
    id: '/drivers',
    path: '/drivers',
    getParentRoute: () => AuthenticatedCoordinatorRoute,
  } as any)
const AuthenticatedCoordinatorCollaborateRoute =
  AuthenticatedCoordinatorCollaborateRouteImport.update({
    id: '/collaborate',
    path: '/collaborate',
    getParentRoute: () => AuthenticatedCoordinatorRoute,
  } as any)
const AuthenticatedCoordinatorCalendarRoute =
  AuthenticatedCoordinatorCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedCoordinatorRoute,
  } as any)
const AuthenticatedAdminLedgerRoute =
  AuthenticatedAdminLedgerRouteImport.update({
    id: '/ledger',
    path: '/ledger',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeatureCostsRoute =
  AuthenticatedAdminFeatureCostsRouteImport.update({
    id: '/feature-costs',
    path: '/feature-costs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-auth': typeof AdminAuthRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/coordinator': typeof AuthenticatedCoordinatorRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/admin/feature-costs': typeof AuthenticatedAdminFeatureCostsRoute
  '/admin/ledger': typeof AuthenticatedAdminLedgerRoute
  '/coordinator/calendar': typeof AuthenticatedCoordinatorCalendarRoute
  '/coordinator/collaborate': typeof AuthenticatedCoordinatorCollaborateRoute
  '/coordinator/drivers': typeof AuthenticatedCoordinatorDriversRoute
  '/coordinator/incoming': typeof AuthenticatedCoordinatorIncomingRoute
  '/coordinator/labels': typeof AuthenticatedCoordinatorLabelsRoute
  '/coordinator/my-driving': typeof AuthenticatedCoordinatorMyDrivingRoute
  '/coordinator/pending': typeof AuthenticatedCoordinatorPendingRoute
  '/coordinator/portal-links': typeof AuthenticatedCoordinatorPortalLinksRoute
  '/coordinator/statements': typeof AuthenticatedCoordinatorStatementsRoute
  '/m/client/$token': typeof MClientTokenRoute
  '/m/driver/$token': typeof MDriverTokenRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/coordinator/': typeof AuthenticatedCoordinatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-auth': typeof AdminAuthRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/c/$token': typeof CTokenRoute
  '/admin/feature-costs': typeof AuthenticatedAdminFeatureCostsRoute
  '/admin/ledger': typeof AuthenticatedAdminLedgerRoute
  '/coordinator/calendar': typeof AuthenticatedCoordinatorCalendarRoute
  '/coordinator/collaborate': typeof AuthenticatedCoordinatorCollaborateRoute
  '/coordinator/drivers': typeof AuthenticatedCoordinatorDriversRoute
  '/coordinator/incoming': typeof AuthenticatedCoordinatorIncomingRoute
  '/coordinator/labels': typeof AuthenticatedCoordinatorLabelsRoute
  '/coordinator/my-driving': typeof AuthenticatedCoordinatorMyDrivingRoute
  '/coordinator/pending': typeof AuthenticatedCoordinatorPendingRoute
  '/coordinator/portal-links': typeof AuthenticatedCoordinatorPortalLinksRoute
  '/coordinator/statements': typeof AuthenticatedCoordinatorStatementsRoute
  '/m/client/$token': typeof MClientTokenRoute
  '/m/driver/$token': typeof MDriverTokenRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/coordinator': typeof AuthenticatedCoordinatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-auth': typeof AdminAuthRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/coordinator': typeof AuthenticatedCoordinatorRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/_authenticated/admin/feature-costs': typeof AuthenticatedAdminFeatureCostsRoute
  '/_authenticated/admin/ledger': typeof AuthenticatedAdminLedgerRoute
  '/_authenticated/coordinator/calendar': typeof AuthenticatedCoordinatorCalendarRoute
  '/_authenticated/coordinator/collaborate': typeof AuthenticatedCoordinatorCollaborateRoute
  '/_authenticated/coordinator/drivers': typeof AuthenticatedCoordinatorDriversRoute
  '/_authenticated/coordinator/incoming': typeof AuthenticatedCoordinatorIncomingRoute
  '/_authenticated/coordinator/labels': typeof AuthenticatedCoordinatorLabelsRoute
  '/_authenticated/coordinator/my-driving': typeof AuthenticatedCoordinatorMyDrivingRoute
  '/_authenticated/coordinator/pending': typeof AuthenticatedCoordinatorPendingRoute
  '/_authenticated/coordinator/portal-links': typeof AuthenticatedCoordinatorPortalLinksRoute
  '/_authenticated/coordinator/statements': typeof AuthenticatedCoordinatorStatementsRoute
  '/m/client/$token': typeof MClientTokenRoute
  '/m/driver/$token': typeof MDriverTokenRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/coordinator/': typeof AuthenticatedCoordinatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-auth'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/coordinator'
    | '/c/$token'
    | '/admin/feature-costs'
    | '/admin/ledger'
    | '/coordinator/calendar'
    | '/coordinator/collaborate'
    | '/coordinator/drivers'
    | '/coordinator/incoming'
    | '/coordinator/labels'
    | '/coordinator/my-driving'
    | '/coordinator/pending'
    | '/coordinator/portal-links'
    | '/coordinator/statements'
    | '/m/client/$token'
    | '/m/driver/$token'
    | '/admin/'
    | '/coordinator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-auth'
    | '/auth'
    | '/sitemap.xml'
    | '/c/$token'
    | '/admin/feature-costs'
    | '/admin/ledger'
    | '/coordinator/calendar'
    | '/coordinator/collaborate'
    | '/coordinator/drivers'
    | '/coordinator/incoming'
    | '/coordinator/labels'
    | '/coordinator/my-driving'
    | '/coordinator/pending'
    | '/coordinator/portal-links'
    | '/coordinator/statements'
    | '/m/client/$token'
    | '/m/driver/$token'
    | '/admin'
    | '/coordinator'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-auth'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/coordinator'
    | '/c/$token'
    | '/_authenticated/admin/feature-costs'
    | '/_authenticated/admin/ledger'
    | '/_authenticated/coordinator/calendar'
    | '/_authenticated/coordinator/collaborate'
    | '/_authenticated/coordinator/drivers'
    | '/_authenticated/coordinator/incoming'
    | '/_authenticated/coordinator/labels'
    | '/_authenticated/coordinator/my-driving'
    | '/_authenticated/coordinator/pending'
    | '/_authenticated/coordinator/portal-links'
    | '/_authenticated/coordinator/statements'
    | '/m/client/$token'
    | '/m/driver/$token'
    | '/_authenticated/admin/'
    | '/_authenticated/coordinator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminAuthRoute: typeof AdminAuthRoute
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CTokenRoute: typeof CTokenRoute
  MClientTokenRoute: typeof MClientTokenRoute
  MDriverTokenRoute: typeof MDriverTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-auth': {
      id: '/admin-auth'
      path: '/admin-auth'
      fullPath: '/admin-auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coordinator': {
      id: '/_authenticated/coordinator'
      path: '/coordinator'
      fullPath: '/coordinator'
      preLoaderRoute: typeof AuthenticatedCoordinatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinator/': {
      id: '/_authenticated/coordinator/'
      path: '/'
      fullPath: '/coordinator/'
      preLoaderRoute: typeof AuthenticatedCoordinatorIndexRouteImport
      parentRoute: typeof AuthenticatedCoordinatorRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/m/driver/$token': {
      id: '/m/driver/$token'
      path: '/m/driver/$token'
      fullPath: '/m/driver/$token'
      preLoaderRoute: typeof MDriverTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/client/$token': {
      id: '/m/client/$token'
      path: '/m/client/$token'
      fullPath: '/m/client/$token'
      preLoaderRoute: typeof MClientTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coordinator/statements': {
      id: '/_authenticated/coordinator/statements'
      path: '/statements'
      fullPath: '/coordinator/statements'
      preLoaderRoute: typeof AuthenticatedCoordinatorStatementsRouteImport
      parentRoute: typeof AuthenticatedCoordinatorRoute
    }
    '/_authenticated/coordinator/portal-links': {
      id: '/_authenticated/coordinator/portal-links'
      path: '/portal-links'
      fullPath: '/coordinator/portal-links'
      preLoaderRoute: typeof AuthenticatedCoordinatorPortalLinksRouteImport
      parentRoute: typeof AuthenticatedCoordinatorRoute
    }
    '/_authenticated/coordinator/pending': {
      id: '/_authenticated/coordinator/pending'
      path: '/pending'
      fullPath: '/coordinator/pending'
      preLoaderRoute: typeof AuthenticatedCoordinatorPendingRouteImport
      parentRoute: typeof AuthenticatedCoordinatorRoute
    }
    '/_authenticated/coordinator/my-driving': {
      id: '/_authenticated/coordinator/my-driving'
      path: '/my-driving'
      fullPath: '/coordinator/my-driving'
      preLoaderRoute: typeof AuthenticatedCoordinatorMyDrivingRouteImport
      parentRoute: typeof AuthenticatedCoordinatorRoute
    }
    '/_authenticated/coordinator/labels': {
      id: '/_authenticated/coordinator/labels'
      path: '/labels'
      fullPath: '/coordinator/labels'
      preLoaderRoute: typeof AuthenticatedCoordinatorLabelsRouteImport
      parentRoute: typeof AuthenticatedCoordinatorRoute
    }
    '/_authenticated/coordinator/incoming': {
      id: '/_authenticated/coordinator/incoming'
      path: '/incoming'
      fullPath: '/coordinator/incoming'
      preLoaderRoute: typeof AuthenticatedCoordinatorIncomingRouteImport
      parentRoute: typeof AuthenticatedCoordinatorRoute
    }
    '/_authenticated/coordinator/drivers': {
      id: '/_authenticated/coordinator/drivers'
      path: '/drivers'
      fullPath: '/coordinator/drivers'
      preLoaderRoute: typeof AuthenticatedCoordinatorDriversRouteImport
      parentRoute: typeof AuthenticatedCoordinatorRoute
    }
    '/_authenticated/coordinator/collaborate': {
      id: '/_authenticated/coordinator/collaborate'
      path: '/collaborate'
      fullPath: '/coordinator/collaborate'
      preLoaderRoute: typeof AuthenticatedCoordinatorCollaborateRouteImport
      parentRoute: typeof AuthenticatedCoordinatorRoute
    }
    '/_authenticated/coordinator/calendar': {
      id: '/_authenticated/coordinator/calendar'
      path: '/calendar'
      fullPath: '/coordinator/calendar'
      preLoaderRoute: typeof AuthenticatedCoordinatorCalendarRouteImport
      parentRoute: typeof AuthenticatedCoordinatorRoute
    }
    '/_authenticated/admin/ledger': {
      id: '/_authenticated/admin/ledger'
      path: '/ledger'
      fullPath: '/admin/ledger'
      preLoaderRoute: typeof AuthenticatedAdminLedgerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/feature-costs': {
      id: '/_authenticated/admin/feature-costs'
      path: '/feature-costs'
      fullPath: '/admin/feature-costs'
      preLoaderRoute: typeof AuthenticatedAdminFeatureCostsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminFeatureCostsRoute: typeof AuthenticatedAdminFeatureCostsRoute
  AuthenticatedAdminLedgerRoute: typeof AuthenticatedAdminLedgerRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminFeatureCostsRoute: AuthenticatedAdminFeatureCostsRoute,
  AuthenticatedAdminLedgerRoute: AuthenticatedAdminLedgerRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCoordinatorRouteChildren {
  AuthenticatedCoordinatorCalendarRoute: typeof AuthenticatedCoordinatorCalendarRoute
  AuthenticatedCoordinatorCollaborateRoute: typeof AuthenticatedCoordinatorCollaborateRoute
  AuthenticatedCoordinatorDriversRoute: typeof AuthenticatedCoordinatorDriversRoute
  AuthenticatedCoordinatorIncomingRoute: typeof AuthenticatedCoordinatorIncomingRoute
  AuthenticatedCoordinatorLabelsRoute: typeof AuthenticatedCoordinatorLabelsRoute
  AuthenticatedCoordinatorMyDrivingRoute: typeof AuthenticatedCoordinatorMyDrivingRoute
  AuthenticatedCoordinatorPendingRoute: typeof AuthenticatedCoordinatorPendingRoute
  AuthenticatedCoordinatorPortalLinksRoute: typeof AuthenticatedCoordinatorPortalLinksRoute
  AuthenticatedCoordinatorStatementsRoute: typeof AuthenticatedCoordinatorStatementsRoute
  AuthenticatedCoordinatorIndexRoute: typeof AuthenticatedCoordinatorIndexRoute
}

const AuthenticatedCoordinatorRouteChildren: AuthenticatedCoordinatorRouteChildren =
  {
    AuthenticatedCoordinatorCalendarRoute:
      AuthenticatedCoordinatorCalendarRoute,
    AuthenticatedCoordinatorCollaborateRoute:
      AuthenticatedCoordinatorCollaborateRoute,
    AuthenticatedCoordinatorDriversRoute: AuthenticatedCoordinatorDriversRoute,
    AuthenticatedCoordinatorIncomingRoute:
      AuthenticatedCoordinatorIncomingRoute,
    AuthenticatedCoordinatorLabelsRoute: AuthenticatedCoordinatorLabelsRoute,
    AuthenticatedCoordinatorMyDrivingRoute:
      AuthenticatedCoordinatorMyDrivingRoute,
    AuthenticatedCoordinatorPendingRoute: AuthenticatedCoordinatorPendingRoute,
    AuthenticatedCoordinatorPortalLinksRoute:
      AuthenticatedCoordinatorPortalLinksRoute,
    AuthenticatedCoordinatorStatementsRoute:
      AuthenticatedCoordinatorStatementsRoute,
    AuthenticatedCoordinatorIndexRoute: AuthenticatedCoordinatorIndexRoute,
  }

const AuthenticatedCoordinatorRouteWithChildren =
  AuthenticatedCoordinatorRoute._addFileChildren(
    AuthenticatedCoordinatorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCoordinatorRoute: typeof AuthenticatedCoordinatorRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCoordinatorRoute: AuthenticatedCoordinatorRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminAuthRoute: AdminAuthRoute,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CTokenRoute: CTokenRoute,
  MClientTokenRoute: MClientTokenRoute,
  MDriverTokenRoute: MDriverTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
